### ISSUE TITLE
fake_useragent 오류가 뜨면서 실행이 되지 않습니다.

### ISSUE THREAD

**Issue by sackdong** [nadane1708/DC_TWICE_Image_Downloader#6]
Traceback (most recent call last):
  File "fake_useragent\utils.py", line 154, in load
  File "fake_useragent\utils.py", line 99, in get_browsers
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_useragent\utils.py", line 67, in get
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 502, in <module>
  File "main.py", line 38, in __init__
  File "dc.py", line 35, in __init__
  File "fake_useragent\fake.py", line 69, in __init__
  File "fake_useragent\fake.py", line 78, in load
  File "fake_useragent\utils.py", line 250, in load_cached
  File "fake_useragent\utils.py", line 245, in update
  File "fake_useragent\utils.py", line 189, in load
  File "fake_useragent\utils.py", line 84, in get
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

이런 로그가 뜨면서 실행이 안되네요

**Comment by nadane1708** [comment]
안녕하세요. 답변이 늦어서 죄송합니다.  
해당 문제를 수정한 버전을 새로 릴리즈 하였습니다.

https://github.com/nadane1708/DC_TWICE_Image_Downloader/releases/tag/v1.65
